$tpl.="<table border='1' style='width: 600px; margin-left: auto; margin-right: auto; padding: 5px; font-family: Lucida sans, Helvetica, Sans-serif; font-size: 11px; border:1px solid #252525'>";
    $tpl.="<tr>";
        $tpl.="<td style='max-width: 60px; padding: 0; border-left: none; border-top: none; border-bottom: none; border-right:1px solid #252525;'>";
            $tpl.="<div style='transform: rotate(-90deg); -webkit-transform: rotate(-90deg); -moz-transform: rotate(-90deg); -ms-transform: rotate(-90deg); font-size: 20px; '>";
                $tpl.="TICKET";
            $tpl.="</div>";
        $tpl.="</td>";
        $tpl.="<td style='width: 480px; border:none;'>";
            $tpl.="<table style='border:none; padding-left: 5px; padding-right: 5px;'>";
                $tpl.="<tr>";
                    $tpl.="<td style='width: 60%; border-left: none; border-top: none; border-bottom: none; border-right:1px solid #252525; padding-right: 5px;'>";
                        $tpl.="<div style='width: auto; margin-top: 5px; margin-bottom: 5px;'>";
                            $tpl.="<div style='width: 32%; float: left;'>";
                                $tpl.="Event <span style='float: right;'>:</span>";
                            $tpl.="</div>";
                            $tpl.="<div style='width: 65%; float: right; padding-left: 5px;'>";
                                $tpl.="OASIS 10 - Where Crowds Collide and Music Comes Alive";
                            $tpl.="</div>";
                            $tpl.="<div style='clear: both;'></div>";
                        $tpl.="</div>";
                        $tpl.="<div style='width: auto; margin-top: 5px; margin-bottom: 5px;'>";
                             $tpl.="<div style='width: 32%; float: left;'>";
                                $tpl.="Date & Time <span style='float: right;'>:</span>";
                            $tpl.="</div>";
                            $tpl.="<div style='width: 65%; float: right; padding-left: 5px;'>";
                                $tpl.="5 Sept 2016, 12:30 pm";
                            $tpl.="</div>";
                            $tpl.="<div style='clear: both;'></div>";
                        $tpl.="</div>";
                        $tpl.="<div style='width: auto; margin-top: 5px; margin-bottom: 5px;'>";
                            $tpl.="<div style='width: 32%; float: left;'>";
                                $tpl.="Location  <span style='float: right;'>:</span>";
                            $tpl.="</div>";
                            $tpl.="<div style='width: 65%; float: right; padding-left: 5px;'>";
                                $tpl.="Gelora Bung Karno";
                            $tpl.="</div>";
                            $tpl.="<div style='clear: both;'></div>";
                        $tpl.="</div>";
                        $tpl.="<div style='width: auto; margin-top: 5px; margin-bottom: 5px;'>";
                            $tpl.="<div style='width: 32%; float: left;'>";
                                $tpl.="Ordered By <span style='float: right;'>:</span>";
                            $tpl.="</div>";
                            $tpl.="<div style='width: 65%; float: right; padding-left: 5px;'>";
                                $tpl.="Mr. Andri";
                            $tpl.="</div>";
                            $tpl.="<div style='clear: both;'></div>";
                        $tpl.="</div>";
                        $tpl.="<div style='width: auto; margin-top: 5px; margin-bottom: 5px;'>";
                            $tpl.="<div style='width: 32%; float: left;'>";
                                $tpl.="Seat  <span style='float: right;'>:</span>";
                            $tpl.="</div>";
                            $tpl.="<div style='width: 65%; float: right; padding-left: 5px;'>";
                                $tpl.="2";
                            $tpl.="</div>";
                            $tpl.="<div style='clear: both;'></div>";
                        $tpl.="</div>";
                        $tpl.="<div style='width: auto; margin-top: 5px; margin-bottom: 5px;'>";
                            $tpl.="<div style='width: 32%; float: left;'>";
                                $tpl.="Price  <span style='float: right;'>:</span>";
                            $tpl.="</div>";
                            $tpl.="<div style='width: 65%; float: right; padding-left: 5px;'>";
                                $tpl.="Rp. 10.000";
                            $tpl.="</div>";
                            $tpl.="<div style='clear: both;'></div>";
                        $tpl.="</div>";
                        $tpl.="<div style='width: auto; margin-top: 5px; margin-bottom: 5px;'>";
                            $tpl.="<div style='width: 32%; float: left;'>";
                                $tpl.="Ticket Type  <span style='float: right;'>:</span>";
                            $tpl.="</div>";
                            $tpl.="<div style='width: 65%; float: right; padding-left: 5px;'>";
                                $tpl.="Standard";
                            $tpl.="</div>";
                            $tpl.="<div style='clear: both;'></div>";
                        $tpl.="</div>";

                    $tpl.="</td>";
                    $tpl.="<td style='width: 40%; text-align: right;'>";

                        $tpl.="<img src='http://everyvents.com/try/assets/img/logo-email.png' style='width: 110px;'>";
                
                        $tpl.="<div style='width: auto; margin-top: 10px; margin-bottom: 15px;'>";
                            $tpl.="Want to make great event ? <br/>";
                            $tpl.="Organized your event with us";
                        $tpl.="</div>";
            
                        $tpl.="<img src='http://everyvents.com/try/assets/img/barcode-ticket.jpg'>";
                      
                        $tpl.="<div style='width: 100%; margin-top: 5px;'>";
                            $tpl.="www.everyvents.com";
                        $tpl.="</div>";

                    $tpl.="</td>";
                $tpl.="</tr>";
            $tpl.="</table>";

        $tpl.="</td>";
        $tpl.="<td style='max-width: 60px; border-left: 1px solid #252525;; border-top: none; border-bottom: none; border-right:none;'>";
            $tpl.="<img src='http://everyvents.com/ev.services/cdn/tickets/barcode/000021500349248.png' style='transform: rotate(-90deg); -webkit-transform: rotate(-90deg); -moz-transform: rotate(-90deg); -ms-transform: rotate(-90deg); margin-left: -15px;'>";
        $tpl.="</td>";
    $tpl.="</tr>";
$tpl.="</table>";